- .mailmap
- _data/contributors.json
- index.md
This commit:
* Adds a mailmap to normalize the names of contributors in git's logs.
* Adds a snapshot of people who have committed to the repository, generated from git.
* Adds any missing people to the homepage.
* Adds a mention of the Data Commons Co-op.
I couldn't track down contact information for "gscalise" but found everyone
else.  I'd be happy to add text on any other contributors and affiliations.
> update list of contributors

- json-table-schema/index.md
See short discussion here: https://github.com/dataprotocols/dataprotocols/issues/172
As an implementor (https://github.com/okfn/jtskit-py), I'll be adding a flag to allow users to enable/disable case sensitivity. As noted in the above discussion, it is very useful of the spec addresses this use case specifically.
> Proposal: Clarify case sensitivity around names (headers)

- json-table-schema/index.md
> Proposal: constraints.oneOf

- json-table-schema/index.md
Examples should probably be valid JSON.
> json-table-schema: add missing commas in examples

- json-table-schema/index.md
To not create unnecessary differences between JTS and JSON Schema.
1. If we later want something with the behavior of JSON Schema's `oneOf` (for example, specifying a validation for a "date" column which can either be an integer (timestamp) or a string with the format "YYYY-MM-DD"), then we'll need to find some new term instead of just using `oneOf` and `enum` in identical meanings to JSON Schema. 
2. It's almost always better to use the same terms as existing, popular prior work to avoid confusion and to avoid potential future conflicts. `oneOf` isn't dramatically clearer than `enum`. `enum` was chosen for JSON Schema for this second reason: `ENUM` is a keyword with identical behavior in SQL (and maybe even other popular prior work). Consistent terms across multiple projects is …
> Rename contraints.oneOf to contraints.enum

- data-packages/index.md
Address issue #214 which discusses unhelpfulness and confusion caused by ``licenses`` property, simplifying it to use only ``license``.
> License xor licenses (solution in favour of license)

- json-table-schema/index.md
Not all constraints are supported by all field types. These commits are an attempt to clarify this and offer a suggestion for implementation behaviour for unsupported constraints. Related to #161.
> Define supported field types for min*/max* constraints

- data-packages/index.md
Licenses was dropped in favor of license on version 1.0.0-beta.14 (issue #214), but there the datapackage's JSON example was still using `licenses`. This PR fixes that.
> Change "licenses" to "license" in sample datapackage

- data-packages/index.md
JSON attributes should be quoted. Also, keep the comments consistent with the rest of the file, using "#" instead of "//".
> Fix JSON examples in Data Packages' spec

- data-packages/index.md
I've been sending these pull requests for tiny improvements in dataprotocols.org, but I'm not sure if they're useful. I wonder if you'd prefer not to fix these small issues now, but do a general revision on the text later, when the schema gets out of beta.
> Fix typos in Data Packages' spec

- data-packages/index.md
Makes it clearer that a `path` in a remote `datapackage.json` is relative to its URL.
> Improve text on resource "path" use when "datapackage.json" is remote

- json-table-schema/index.md
> Typo on date specification

- json-table-schema/index.md
This just avoids any confusion between what's in the changelog and what's in the spec.
> Typo: `missingValues` -> `missingValue`

- content/implementation/contents.lr
Implementation links have changed to the most up to date implementations.
> Updated implementation links

- content/implementation/contents.lr
Wording for dereferencing requirements pre-validation, added as an implementation note, and not as part of core specs, as per https://github.com/frictionlessdata/specs/issues/365
Closes https://github.com/frictionlessdata/specs/issues/365
While this is ~ mergeable, I'm quite happy to discuss this as much as needed.
Related, I'm also wondering if we should open up our validation process to be less strict - essentially, have a "light" validation that just runs the base dp descriptor validation, no matter what the profile - as that would address some comments recently by @rufuspollock where he wants to essentially bypass validation.
> Dereferencing wording for implementors

- README.md
Just getting started with open data and the frictionlessdata spec.
This was a small hiccup in the "Quick start" -- at least for me.
> "npm compile" -> "npm run compile"

- sources/dictionary/common.yml
Current spec was breaking python `jsonschema` library validation because of hyphen inside character class - http://stackoverflow.com/questions/28539253/python-regex-bad-character-range.
I'm putting hyphen to the safe place (as an option it could be escaped).
> Fixed pattern for name in common.yml

- sources/dictionary/common.yml
> `name` — An identifier string. Lower case characters with `.`, `_`, `-` and `/` are allowed.
> Update example license name to fit stated requirements

- content/table-schema/contents.lr
The word `<PATTERN>` is interpreted as an HTML tag in markdown so it isn't rendered as you can see below:
I replaced `<PATTERN>` with `{PATTERN}` which was already used in the docs.
> Replace accidental use of "<" in markdown

- sources/dictionary/tableschema.yml
- connects https://github.com/frictionlessdata/tableschema-js/issues/70
---
Because `datetime/date/time` types in Table Schema could have format in a form of `<PATTERN>` we can't use `enum` for it.
> Fixed pattern format for datetime/date/time types

- content/table-schema/contents.lr
- sources/dictionary/tableschema.yml
- Closes #415
@akariv @roll @rufuspollock note that this is *not* a property at the same level as `missingValues`, which is what I indicated in #415 . Rather, these are two properties applicable to BooleanFields.
> trueValues and falseValues for boolean fields

- sources/dictionary/common.yml
* try to validate a descriptor with path fields containing relative file name
* for example:
```
{"resources": [
{"name": "my-resource", "data": ["data/my-resource.csv"]}
]}
```
* should validate with most common json schema validators
* should conform to json schema spec
* this fails validation using [Php JsonSchema](https://github.com/justinrainbow/json-schema)
* the reason is that path / data is defined in spec as string with format `uri`: [dictionary/common.yml#L112](https://github.com/frictionlessdata/specs/blob/master/sources/dictionary/common.yml#L112)
* in the [json schema spec](http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3.6) this is defined as:  ```A string instance is valid against this attribute if it is a valid URI, according to RFC3986```
* …
> path should be plain string format, not uri

- sources/dictionary/tableschema.yml
Because of typo in `dictionaries` jsonschema for Table Schema itself was invalid.
Current:
https://specs.frictionlessdata.io/schemas/table-schema.json
http://www.jsonschemavalidator.net/
> Fixed table schema foreign keys

- content/profiles/contents.lr
- sources/dictionary/common.yml
- sources/dictionary/package.yml
- sources/dictionary/resource.yml
- templates/partials/profiles.html
Small changes that make things a bit more clear:
- updated the registry link
- referred to the default profiles by their name in the registry
- mentioned the existence of Tabular Data Resource since, as far as I understood, people should be able to use it independently from Tabular Data Package
> Update profile specs

- schemas/dictionary.json
- schemas/dictionary/common.yml
According to the written specs:
> The value for the schema property on a resource MUST be an object
> representing the schema OR a string that identifies the location of
> the schema.
But the current JSON schema does not allow URLs or paths in the `schema`
property:
```
jsonschema.exceptions.ValidationError:
'http://iatistandard.org/202/schema/downloads/iati-activities-schema.xsd'
is not of type 'object'
```
I'm not 100% of how the specs are rebuilt, but this PR includes:
* Changes in `schemas/dictionary/common.yml` to allow a path in the
`schema`.
* After running `npm run build`, `schemas/dictionary.json` is updated.
Let me know if this is not the right approach for rebuilding the
schemas.
> Allow path and object on Resource schema property

- schemas/dictionary.json
- schemas/dictionary/dialect.yml
According to the [JSON Schema](https://frictionlessdata.io/schemas/csv-dialect.json) for CSV Dialect,
```
"quoteChar": {
"title": "Quote Character",
"description": "Specifies a one-character string to use as the quoting character.",
"type": "string",
"default": "\"",
"examples": [
"{\n  \"quoteChar\": \"\"\n}\n",
"{\n  \"quoteChar\": \"''\"\n}\n"
]
}
```
But neither the empty string `""` nor the double single-quote `"''"` is a one-character string(?). In this pull request, I propose to use the single single-quote `"'"` as the main example instead.
> Set quoteChar to one-character string

- package.json
- schemas/dictionary.json
- schemas/dictionary/common.yml
- test/schemas.js
See the original issue here - https://github.com/frictionlessdata/tableschema-js/issues/133
As stated in https://frictionlessdata.io/specs/data-resource/#data-location, specs shouldn't accept a path that starts with `.` (which also includes `..`), `/` or `~`.
The security notice doesn't mention that `~` and `./` are forbidden.
> Added a pattern for 'path' property

- schemas/dictionary/tableschema.yml
- specs/table-schema.md
Allow setting no entries for the missingValues property in tableschema.
See #578 for details.
> [#578] Allow empty missing values

- specs/data-package.md
and apply a consistent approach to code examples using
```javascript
code example
```
fixes #559
> fix "contributors" example

- schemas/dictionary/common.yml
add "title" for a complete example
fixes #581
> fix licenses example "path" not "uri"

- specs/patterns.md
Removes option to refer to data package `name` as no explanation offered in [forum](https://discuss.okfn.org/t/foreign-keys-across-data-packages/6460?u=stephen), [gitter](https://gitter.im/frictionlessdata/chat?at=5aa04d8d26a769820b2a769c) or [github](https://github.com/frictionlessdata/specs/issues/597).
Fixes #597
> Add overview and example to Foreign Keys to Data Packages pattern WIP

- schemas/dictionary/dialect.yml
Field `csvddfVersion` is specified in the specification text but not in this schema.
> Add field csvddfVersion to CSVDDF schema

- specs/csv-dialect.md
[Version 1.0 of CSVDDF](http://dataprotocols.readthedocs.io/en/latest/csv-dialect.html) is incompatible with version 1.2 so the example should not refer to 1.0. Also provide a full JSON example instead of malformed fragment.
> Change csvddfVersion to 1.2 to fix example

- specs/tabular-data-resource.md
To make the specs clearer that users can just reference an external JSON document. As discussed [on the forum](https://discuss.okfn.org/t/shared-table-schema/6969).
> make explicit referencing an external JSON document for Table Schema

- specs/table-schema.md
The key is still "format", not "pattern".
> Correct datetime pattern example

- README.md
Minor correction `compile.js` -> `build.js`
> Fix filename in README.md

- schemas/dictionary/dialect.yml
- specs/csv-dialect.md
As discussed in #254 I'd propose re-opening that discussion and probably include a comment char in the dialect spec.
> Add `commentChar` field to CSV dialect spec

- specs/patterns.md
Follows #627 and #384 
This PR is marked as draft because before merging I'd like to discuss those questions with maintainers:
- I kept the `id` property, but is it relevant for schemas?
- Shouldn't there be an `updated` property, to go with `created`?
- Can we reuse `resources` for example CSV files? Even if the resource is invalid (in order to illustrate errors)?
- Can we reuse `source` to link to the document (i.e. a PDF file) that preceded the tableschema in JSON format?
- Why is `version` documented on [the website](https://frictionlessdata.io/specs/data-package/) but not present in `package.yml`?
> Add pattern for Table Schema metadata

- specs/patterns.md
WIP for specs outlined in the data catalogue discussion: https://github.com/frictionlessdata/specs/issues/37#issuecomment-486745545
* adds a `document-data-resource` spec
* begins a `data-package-resource` spec
* minor edits to other docs to have more uniform style
I'm not entirely sure if `data-package-resource`s should be inherited from document resources, as while they _are_ structured documents, it creates a confusion of media types.
> Document resources, Data package resources

- specs/patterns.md
The name `json5` breaks the lektor build on the main FD website:
specs/patterns/index.html (ClassNotFound: no lexer for alias u'json5' found)
https://travis-ci.org/frictionlessdata/website/builds/561974893
> Fix language name on JSON code snippets

- specs/patterns.md
- specs/table-schema.md
- Clarify that fields are not required unless explicitly set to `true`.
- Specify that `primaryKey` fields are required.
- Add a pattern for `uniqueKeys` which implements the SQL UNIQUE constraint.
per https://github.com/frictionlessdata/specs/issues/593 and https://github.com/frictionlessdata/goodtables-py/pull/252. Replaces my previous pull request https://github.com/frictionlessdata/specs/pull/642.
> Add pattern for defining row uniqueness constraints with Table Schema

- specs/patterns.md
Per followup discussion in https://github.com/frictionlessdata/specs/issues/593.
- Adds `uniqueNulls` property controlling how `null` values are treated in unique constraints
- Updates the pattern for `uniqueKeys` accordingly
- Extends the `foreignKeys` specification with regards to `null` values
> Add uniqueNulls property to unique constraints pattern

- schemas/dictionary/common.yml
Added the [proposed fix](https://github.com/frictionlessdata/specs/issues/645) to the YAML sources
> fix for frictionlessdata/specs/issues/645

- specs/patterns.md
The overview should be consistent with the specification in that foreign key references to another data package are allowed (#653).
> allow FK references to different data packages (fix #653)

- schemas/dictionary.json
- schemas/dictionary/tableschema.yml
Derived from https://github.com/frictionlessdata/tableschema-py/pull/267
It removes pattern constraint from:
- number
- integer
- yearmonth
---
It also includes an addition of `commentChar` to `schemas` which probably was forgotten to built previously.
> Remove pattern constraint from number/integer/yearmonth schemes

- schemas/dictionary.json
This is closely related to https://github.com/frictionlessdata/specs/issues/645 and describes basically the same bug, just for the way
According to human-readable spec (https://specs.frictionlessdata.io/tabular-data-resource/#csv-dialect), Dialect should bei either a JSON object or a file reference.
The value for the dialect property on a resource MUST be an object representing the dialect OR a string that identifies the location of the dialect.
If a string it must be a url-or-path, that is a fully qualified http URL or a relative POSIX path. The file at the the location specified by this url-or-path string MUST be a JSON document containing the dialect.
The corresponding definition, however, disallows paths or URLs and only allows JSON objects:
"csvDialect": {
"title": "CSV Dialect", …
> Data Resource JSON schema definition for `dialect` seems to contradict specification

- schemas/dictionary/dialect.yml
- specs/csv-dialect.md
Per our discussion in issue #254, I've built upon #624 to simplify the behavior we're expecting. Otherwise, there are different interpretations of the behavior a `commentChar` could have and there is varied support is across different CSV parsers. The approach here sets a baseline for what a comment should do at minimum which we can later extend with additional attributes if need be.
Is it worth bumping up the version number? In theory this breaks compatibility with the previous description of `commentChar` even though this updated definition is in line with the original motivation of adding this feature.
> Restricting `commentChar` to ignore a line only if it appears at the start

- specs/table-schema.md
Backticks aren't parsed as Markdown here for some reasons, so I switched everything to the HTML version.
Prod URL: https://specs.frictionlessdata.io/table-schema/#constraints
> TableSchema: backticks to code in table

- .vuepress/config.js
- tabular-diff/README.md
This brings back a page about a tabular diff format, per https://github.com/frictionlessdata/project/issues/361.  Previously introduced in #64. Some information about repo history since then at https://github.com/frictionlessdata/project/issues/369.
> bring back the tabular diff format spec

- data-package/README.md
- data-resource/README.md
- fiscal-data-package--budgets/README.md
- fiscal-data-package--spending/README.md
- fiscal-data-package/README.md
:wave: I've never contributed to this project before &ndash; I just saw some broken links on the website and thought the easiest/most helpful thing to do would be to just raise a PR. Apologies in advance if there are any guidelines/conventions I'm unaware of and should have adhered to.
Change internal links (i.e. to other specifications) that are pointing to `/specs/...` to point to `/...`.
These links are currently broken on the <http://specs.frictionlessdata.io/> site.
**Example:** Visit <http://specs.frictionlessdata.io/data-package/#descriptor>, and click the "Tabular Data Package" link below the first code example in this section. You will see a 404. Removing `specs/` from the URL takes you to the right page.
**Caveat:** I haven't tested these changes locally, but I have checked each …
> Fix broken links

- table-schema/README.md
See #704: strongly recommend, but do not require **order of fields** to be the same in schema as csv (`MUST` -> `SHOULD`). The **number of fields** was already strongly recommended, but not required. This change allows one to use external (community adopted) schemas with fewer or more fields in a different order. It is also already implemented as such in frictionless-py (`sync-schema` option).
I also removed the word "exactly" in:
> The number of elements in `fields` array `SHOULD` be ~exactly~ the same as the number of fields in the CSV file.
... as it seems a bit odd to use in combination with "should" and it is not used for "order" either.
> Do not require order of fields to be the same in schema as csv

- patterns/README.md
This is a 'rebase' of #608 'Missing value per field pattern'.  I didn't find a straight forward way to pull the original commit da1660d  from `specs/patterns.md`to the new file `patterns/README.md`.  So this change manually takes the change content of da1660d and adds it to the bottom of the current file.   It didn't look like there was any particular order to the sections in `patterns/README.md` so I added da1660d's content to the end of the file.  Let me know if this needs to be moved and I'll make the change.
Author: Stephen-Gates <Stephen.Gates@me.com>
Date:   Sat Apr 7 20:40:44 2018 +1000
WIP missing value per field pattern
as per https://discuss.okfn.org/t/missing-values-per-field-pattern/6571
If this change is no longer desired, go ahead and close this pull request.  
If this …
> Rebase da1660d: 'missing value per field pattern'

- patterns/README.md
At https://specs.frictionlessdata.io/patterns/#specification-3 there is an example stating:
> Example of a compressed resource with the compression property:
But the actual example does not have the `compression` property. In fact, it just removes the `encoding` property compared with the example above. This is clearly incorrect.
I can't find out with "blame" what happened to the example or why, so I have corrected it to what was originally proposed in https://github.com/frictionlessdata/specs/pull/629/ when compression was introduced. That original proposal is also a bit more verbose: it includes `format` and `mediatype`.
> Correct compression examples

- schemas/dictionary.json
- schemas/dictionary/common.yml
According to the specs - https://specs.frictionlessdata.io/data-package/#contributors - it should be with Z
> Fix JSON Schema "organisation -> organization"

- fiscal-data-package--budgets/README.md
- fiscal-data-package--spending/README.md
- patterns/README.md
* Complements the work done in d2cd3aaa454541c883bd9514186148e28c22541c
* Fixes #693
Changes made to `patterns/README.md` in particular were necessary as the examples went against the specs.
> [spelling][xs]: Spell organisation as organization

- csv-dialect/README.md
- schemas/dictionary/dialect.yml
- fixes #684 
---
It was originally False in goodtabes/frictionless so we don't need to change it
> Set dialect.skipInitialSpace defaults to False

- .vuepress/enhanceApp.js
* Redirect `/simple-data-format/` to `/tabular-data-package/`
* Fixes #535
There is no longer any occurrence of the route `/simple-data-format` in the repo, but this takes into account the original one that existed. Additionally, the page `/guides/tabular-data-package/` is now found at `/tabular-data-package/`, so the redirect is pointing there: https://specs.frictionlessdata.io/tabular-data-package/
> [redirects][s]: Redirect for `simple-data-format`

- .vuepress/config.js
* Set absolute path to the main repo so that changes will be kept in sync.
* Use URL https://frictionlessdata.io/img/frictionless-color-logo.svg instead of https://frictionlessdata.io/img/frictionless-color-full-logo.svg because we only need to display the logo without additional text.
* Fixes https://github.com/frictionlessdata/project/issues/481.
> [logo][xs]: Update URL to new Frictionless logo

- README.md
- data-resource/README.md
@lwinfree and @roll, I'm trying to help solve the problem listed in #755.
As I haven't worked with VUE it was a litter difficult to find the command `npm start` to start my local server and see my new documentation in action, so I'm suggesting including this litter information [Quick Start](https://github.com/frictionlessdata/specs#quick-start) section at README.md file. 
Another point was that the command `npm run test` failed even when I run it without any code changes. Is that normal or did I misunderstand something from the documentation?
> Add name data resource

- data-resource/README.md
Under Metadata Properties, it is recommended for `name` to drop the extension. Updating minimal examples to reflect that recommendation.
> Tweak DataResource docs

- schemas/dictionary/common.yml
According to https://specs.frictionlessdata.io/data-package/#licenses
> licenses MUST be an array. Each item in the array is a License. Each MUST be an object. **The object MUST contain a name property and/or a path property**. It MAY contain a title property.
This was not enforced by the specs (i.e. a license could be added that had neither of those properties). This PR adds that condition (I hope).
> Enforce that `license` has `name` or `path`

- schemas/dictionary.json
- schemas/dictionary/common.yml
- schemas/dictionary/tableschema.yml
- table-schema/README.md
Add a new optional field, `example` for Table Schema fields. `example` can be used to provide an example value for each. This helps producers/reusers know what values are allowed. This can also be use to build example files with sensible values.
@roll, I skipped the pattern phase and I'm proposing directly a spec update as @johanricher suggested in https://github.com/frictionlessdata/specs/issues/740#issuecomment-925060185
> Table Schema: add optional examples for fields

- table-schema/README.md
- Fixed url of link 'Elasticsearch types' in page http://0.0.0.0:8080/table-schema/#types-and-formats.
- Replaced url from http://www.elasticsearch.org/guide/reference/mapping/ to https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html
- fixes #782
> Fixed url for link Elasticsearch types

- schemas/dictionary.json
- schemas/dictionary/common.yml
Related issues: https://github.com/frictionlessdata/tableschema-ui/issues/11
The [documentation](https://specs.frictionlessdata.io/data-package/) says
> The object MUST contain a name property and/or a path property.
The JSON Schema has a bug because a JSON Schema validator (e.g. https://www.jsonschemavalidator.net/) will tell you
>  Found 1 error(s)
> Message: JSON is valid against more than one schema from 'oneOf'. Valid schema indexes: 0, 1.
> Schema path: #/properties/licenses/items/oneOf
for
```
"licenses": [
{
"name": "CC0-1.0",
"title": "CC0 1.0",
"path": "https://creativecommons.org/publicdomain/zero/1.0/"
}
]
```
> Fix licenses JSON Schema

- tabular-data-package/README.md
The example on https://specs.frictionlessdata.io/tabular-data-package/#example is currently not valid, because the resource is missing a `name` property.
I added one called `data` (after `data.csv`), and order the terms as:
- profile
- name
- path
Similar to how those terms are listed in https://specs.frictionlessdata.io/tabular-data-resource/#examples
> Make tabular-data-package example valid

- csv-dialect/README.md
The specification should better state explicitly that `commentChar` is not set by default.
> csv-dialect: make clear commentChar has no default

- csv-dialect/README.md
If I have a json datapackage where it is not present, can I consider it to be the comma?  I think yes, since frictionless describe doesn't produce the delimiter information, when the delimiter is the comma.
> About lack of separator definition

- table-schema/README.md
The table in [constraints](https://specs.frictionlessdata.io/table-schema/#constraints) contains a link to the regex spec, but is rendered as plain markdown, because the text is wrapped in a html table cell `<td>`:
```
[XML Schema regular expression syntax](http://www.w3.org/TR/xmlschema-2/#regexs)
```
Depending on the Markdown parser used to render the pages, there are solutions around this (e.g. write the table as a markdown table, or add the `markdown=1` property). But since the other formatting in the table is done as html (e.g. `<code> MUST</code>`), I simply opted here to convert the markdown link to a `<a>` link.
> Change markdown link to html link, so it renders on website

- schemas/dictionary/tableschema.yml
`"type": "number"` is functionally required on these objects, since an object lacking that property is supposed to be understood as a tableSchemaFieldString instead, per:
https://github.com/frictionlessdata/specs/blob/9e4d58012d80190574d0a1d7038abe4924f9e714/table-schema/README.md?plain=1#L147-L148
> fix(schemas): Require `type` on tableSchemaFieldNumber

- schemas/dictionary/tableschema.yml
Refining this type gives a much better codegen experience. Using [typify](https://crates.io/crates/typify) with `anyOf` yields:
```rust
pub struct TableSchemaField {
#[serde(flatten, default, skip_serializing_if = "Option::is_none")]
pub subtype_0: Option<StringField>,
#[serde(flatten, default, skip_serializing_if = "Option::is_none")]
pub subtype_1: Option<NumberField>,
#[serde(flatten, default, skip_serializing_if = "Option::is_none")]
pub subtype_2: Option<IntegerField>,
#[serde(flatten, default, skip_serializing_if = "Option::is_none")]
pub subtype_3: Option<DateField>,
#[serde(flatten, default, skip_serializing_if = "Option::is_none")]
pub subtype_4: Option<TimeField>,
#[serde(flatten, default, skip_serializing_if = "Option::is_none")]
pub subtype_5: Option<DateTimeField>, …
```
> feat(schemas): Change `anyOf` to `oneOf`

- patterns/README.md
This pull request adds a pattern for supporting the use of value labels and categoricals (sometimes called factors), as requested by @rufuspollock [here](https://github.com/frictionlessdata/specs/issues/156#issuecomment-1040301357). Comments and feedback are welcome.
> Add pattern supporting use of value labels, categoricals and factors

- patterns/README.md
This pull request adds a pattern to express relationships between Fields and define associated validation tool. 
This PR follows the issue #803  and is proposed by @roll.
Several option are proposed for the associated Descriptor.
Thank you very much for your review and comments.
Note: I also added a Table of contents
> Add pattern  -  Table Schema: Relationship between Fields

- package.json
- schemas/context/README.md
- schemas/context/data-package.json
- test/files/data-package-1.json
- test/files/data-package-1.nt
- test/rdf.js
This adds a JSON-LD context for data-package.json with unit test as started to discuss on #869.
> Add JSON-LD Context Document for Data Package
