json-table-schema/index.md
Adds uuid as a string format. See #176.
=> Proposal: Add uuid as a string format

json-table-schema/index.md
=> Fix wrong digits from true/false

json-table-schema/index.md
**DO NOT MERGE**
See #171. This is not ready for merge, just sketching it out. Any help would be appreciated.
=> Proposal: translations and languages

data-packages/index.md
Done as per the discussion on #85.
=> Note the preferred way to include non-MD5 hashes

json-table-schema/index.md
=> self-referencing foreign key support.

data-packages/index.md
=> Update the license id in Data Package examples

data-packages/index.md
=> Change the use of hash to object to fit in with JSON spec

csv-dialect/index.md
=> Document TSV supporting options

_layouts/container.html
=> Add hover link for h2->h6

_includes/example-data.html, _includes/specifications.html, css/style.css, index.md
Dependent on https://github.com/openspending/fiscal-data-package/pull/163
=> Prep for FDP submodule

data-packages/index.md
=> Clarify usage of data property on any resource descriptor

databags/schemas.json, sources/dictionary.json
=> Remove `g` prefix. Closes #346

databags/schemas.json, sources/dictionary.json
As per https://github.com/frictionlessdata/specs/issues/237#issuecomment-277511063
=> Adds ID field. Closes #237

content/implementation/contents.lr
- fixes stack readme link
---
@pwalsh 
@danfowler 
@jobarratt 
WDYT - should we name our low-level libraries (I'm responsible for):
- FrictionlessData Stack OR
- FrictionlessData Core OR
- ?
=> Fixed stack readme link

content/data-resource/contents.lr
A few loose ends ends from #414
=> Fix `data` -> `path` references in Data Resource intro examples

content/implementation/contents.lr
=> Fixed implementation links

sources/registry.csv
Closes https://github.com/frictionlessdata/specs/issues/442
=> Add Table Schema to registry.

sources/dictionary/common.yml, sources/dictionary/resource.yml
Refs. #425 (update schemas to reflect new naming).
=> URI to path, and, data to path, supported by custom resourcePath.

content/tabular-data-resource/contents.lr
Closes https://github.com/frictionlessdata/specs/issues/440
=> Add dialect example.

content/table-schema/contents.lr
=> Fix format and constraints wording.

content/implementation/contents.lr
=> Update info on dereferencing for implementation.

content/data-package/contents.lr
=> Resources property is required.

content/table-schema/contents.lr
=> Introduce physical and logical model concepts.

content/table-schema/contents.lr
=> Clarify physical and logical for constraints.

content/table-schema/contents.lr, sources/dictionary/tableschema.yml
=> Revert to allowing string or array for pk and fk.

sources/dictionary/resource.yml
=> [WIP] Revert resources data property from data to path.

content/table-schema/contents.lr
=> Improve wording around missingValues and required.

sources/dictionary/tableschema.yml
=> Fix foreign keys

sources/dictionary/tableschema.yml
=> Handle constraint types more accurately.

sources/compile.js, sources/dictionary/tableschema.yml
- it makes profile errors not passable on travis  
- fixes `tableSchemaConstraintEnumBoolean`
=> Make compile.js exit on errors, fix boolean enum

sources/dictionary/tableschema.yml
=> Allow any string for a table schema field name.

sources/dictionary/common.yml, sources/dictionary/resource.yml
=> Fix discrepancies between narrative specs, and schemas

content/data-package/contents.lr, content/data-resource/contents.lr, content/tabular-data-package/contents.lr, content/tabular-data-resource/contents.lr
=> Add profile property explicitly in narrative spec and examples.

content/table-schema/contents.lr, sources/dictionary/tableschema.yml
- Closes #258 
- Closes #426
- Closes frictionlessdata/tableschema-py#138
=> Add stripNonNumeric to Integer and Number fields

sources/dictionary/resource.yml
- Closes #501
@georgiana-b can you please review.
=> Fix required fields on resources.

sources/registry.csv
=> Add resource profiles to registry.csv

content/table-schema/contents.lr
=> Fixed bareNumber for integer type

content/data-package/contents.lr, sources/dictionary/common.yml, sources/dictionary/package.yml, sources/dictionary/resource.yml
- Fixes #511 
- Fixes #512 
- Fixes #513 
- Fixes #514
=> Errata due to maintaining across spec and schema.

content/patterns/contents.lr
This PR proposes a new pattern for data package versions
fixes #421
(couldn't get Lector working locally so please test)
=> add data package versions

specs/data-package.md
See https://www.crossref.org/display-guidelines/
=> Change DOI style to use Crossref recommendation

schemas/dictionary.json, schemas/dictionary/common.yml
Reverts frictionlessdata/specs#555
---
Reason - https://github.com/frictionlessdata/specs/pull/555#issuecomment-356856538
=> Revert "Allow path and object on Resource schema property"

specs/table-schema.md
=> \<PATTERN\> fixes #530

specs/tabular-data-resource.md
- improve examples
- fix typo "charactors"
- splits up #565 submitting https://github.com/Stephen-Gates/specs/commit/3f38ab09578ded619fd0969964a380ead7379bc1 only
=> add csv at url

specs/data-package.md
=> reference data package version pattern

specs/tabular-data-package.md
=> add tablular data resource to example

schemas/dictionary.json, schemas/dictionary/dialect.yml
=> Do not set escapeChar by default

specs/csv-dialect.md
as no where in this spec does it specify this!
It is mentioned in https://frictionlessdata.io/specs/tabular-data-resource/#introduction
=> add dialect to text and example

specs/patterns.md
as discussed on https://discuss.okfn.org/t/data-package-versions/6413/9?u=stephen
=> update data package versions

schemas/dictionary/common.yml
fixes #580
not sure if it should be `minItems: 0` or just delete line. @rufuspollock please review
=> make sources optional and fix example

specs/views.md
=> Use named datasets in Vega

schemas/dictionary/common.yml
Tested using https://regex101.com/. Relates to #601
=> Fix invalid path pattern

specs/patterns.md, specs/table-schema.md
Fixes #319
Advice needed on SHOULD or MUST for, 
> The number of elements in `fields` array `SHOULD` be exactly the same as the number of fields in the CSV file.
Wording taken from #319 but in #367 I think @roll may suggest `MUST`
=> Add clarity about fields order and completeness WIP

specs/patterns.md
as [discussed on Gitter](https://gitter.im/frictionlessdata/chat?at=5ad4bc1315c9b0311401783b)
=> use package not datapackage in foreign keys pattern

specs/data-resource.md
fixes #594
Note version number not updated.
Add full-stop for consistency.
=> add IANA link for mediatype

schemas/dictionary.json, schemas/dictionary/dialect.yml
- fixes #616 
---
This reverts commit b5a8daf68584088408d29ee4251176cc800e9b89 + rebuilds the schemas
=> Fix CSV Dialect for the schemas

specs/patterns.md
Added a pattern for compressed resources as suggested by @rufuspollock here: https://github.com/frictionlessdata/specs/issues/290
=> Added a pattern for compressed resourses

specs/patterns.md
=> add Michael Rosenthal as author on patterns.md

specs/patterns.md
Should be "JSON Data Resource" as discussed in #632
=> Fix improperly named document data resource

specs/implementation.md
Adding the R implementation by @christophergandrud - following up on #538
=> Add R implementation to list of references

data-resource/README.md
Part of a fix for #667. I'll run the docs over a broken links tester to find more broken links.
=> [docs][s] - fix broken link and formatting

data-package/README.md
=> [fix][xs]- fix data resource broken link

schemas/dictionary.json, schemas/dictionary/tableschema.yml
- connects https://github.com/frictionlessdata/frictionless-py/issues/553
=> Ensure proper boolean format

.vuepress/config.js
Adding a "Back to the main site" link as on other Frictionless subdomains
=> Added "Back to the main site" link

.vuepress/config.js, package.json, yarn.lock
Just adding the `Plausible` script and removing Google Analytics reference
=> Google Analytics to Plausible

tabular-data-package/README.md
Related to https://github.com/frictionlessdata/frictionless-py/issues/1177
=> Fix example that raises package-error "not valid under any of the given schemas"
